"""Sync Schema

Revision ID: ab31c7fca067
Revises: fa1f34723154
Create Date: 2026-02-19 18:04:05.459291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab31c7fca067'
down_revision = 'fa1f34723154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appraisal_cycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minimum_service_months', sa.Integer(), nullable=False, server_default='3'))
        batch_op.add_column(sa.Column('eligibility_cutoff_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('include_probation_employees', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('prorated_evaluation_allowed', sa.Boolean(), nullable=False, server_default=sa.text('true')))
        batch_op.add_column(sa.Column('new_joiner_policy', sa.String(length=50), nullable=False, server_default='AUTO_INCLUDE_IF_ELIGIBLE'))

    with op.batch_alter_table('appraisals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_prorated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('eligibility_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('eligibility_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appraisals', schema=None) as batch_op:
        batch_op.drop_column('eligibility_reason')
        batch_op.drop_column('eligibility_status')
        batch_op.drop_column('is_prorated')

    with op.batch_alter_table('appraisal_cycles', schema=None) as batch_op:
        batch_op.drop_column('new_joiner_policy')
        batch_op.drop_column('prorated_evaluation_allowed')
        batch_op.drop_column('include_probation_employees')
        batch_op.drop_column('eligibility_cutoff_date')
        batch_op.drop_column('minimum_service_months')

    # ### end Alembic commands ###
