"""add workflow columns

Revision ID: f68da87f988a
Revises: 
Create Date: 2026-02-17 13:35:56.989825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f68da87f988a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appraisals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('self_submitted', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('manager_submitted', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('goal_ratings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('manager_goal_ratings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appraisals', schema=None) as batch_op:
        batch_op.drop_column('manager_goal_ratings')
        batch_op.drop_column('goal_ratings')
        batch_op.drop_column('manager_submitted')
        batch_op.drop_column('self_submitted')

    # ### end Alembic commands ###
