"""Initial migration

Revision ID: 579ba6269e1a
Revises: 
Create Date: 2026-03-05 20:50:15.842167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '579ba6269e1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appraisals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appraisals_status'))

    with op.batch_alter_table('goal_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goal_template_orgwide_uc'), postgresql_where='(department_id IS NULL)')
        batch_op.drop_index(batch_op.f('ix_goal_templates_department'))

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_approval_status'))
        batch_op.drop_index(batch_op.f('ix_goals_employee_cycle'))
        batch_op.drop_index(batch_op.f('ix_goals_status'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_read'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_recipient_read'), ['recipient_id', 'is_read'], unique=False)

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_employee_cycle'), ['employee_id', 'appraisal_cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_approval_status'), ['approval_status'], unique=False)

    with op.batch_alter_table('goal_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goal_templates_department'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goal_template_orgwide_uc'), ['cycle_id', 'title'], unique=True, postgresql_where='(department_id IS NULL)')

    with op.batch_alter_table('appraisals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appraisals_status'), ['status'], unique=False)

    # ### end Alembic commands ###
